version: '2'
services:
    ejemplo-app:
        image: ejemplo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ejemplo-mysql:3306/ejemplo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8090:8090
    ejemplo-mysql:
        extends:
            file: mysql.yml
            service: ejemplo-mysql
